theme: jekyll-theme-minimal
<!DOCTYPE html>
<html>
<head>_</head>
<body>
<div class="wrapper">
<header>
<h1></h1>
<o></p> == $0
</header>
<section>_</section>
<footer></footer>
</div>
<script src="/assets/is/scale.fix.is"></script>
</body>
</html>
